version: "3"

services:
  backend:
    build:
      context: ./src
      dockerfile: ../Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
  db:
    image: postgres:13.21-alpine3.21
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  redis:
    image: redis:alpine3.22
    restart: always
    ports:
      - "6379:6379"

volumes:
  db_data: